version: '2'
services:
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
